### PR TITLE
fix: Ensure filetype is set in sidebar mode

### LINKED ISSUE #141: sidebar toggle does not respect FileType autocommands
I want to `setlocal` some things for the filetype `carbon.explorer`. However, `FileType` autocommands are not triggered when entering the carbon explorer via `ToggleSidebarCarbon` or `ToggleSidebarExplore`. If I manually `setl filetype=carbon.explorer`, then the settings are applied. This does not happen if I `:e .` in a split.

I use the default carbon setup, and my own function for setting filetype autocommands:

```lua
local function setl_ft_autocmd(filetypes, options)
    local cmdparts = {}
    for k, v in pairs(options) do
        if type(v) == "boolean" then
            if v then table.insert(cmdparts, k) else table.insert(cmdparts, "no" .. k) end
        else
            table.insert(cmdparts, k .. "=" .. v)
        end
    end
    api.nvim_create_autocmd({ "FileType" }, {
        pattern = table.concat(filetypes, ","),
        group = filetype_rules,
        command = "setlocal " .. table.concat(cmdparts, " "),
    })
end
```

This works for everything except:

```lua
setl_ft_autocmd({ "carbon.explorer" }, { signcolumn = "no" , cursorline = true })
```

~~Don't know much rust~~ (got confused with other plugin) but could work on a patch if maintainers are busy.

NeoVim 0.10.1, carbon 0.20.2

### PR DESCRIPTION
**Pull request by adigitoleo**
Closes #141.

### CODE REVIEW

**Comment by SidOfc** [comment]
Cheers for the PR!

Was just reading the issue and saw you already created a fix, always appreciated!
I just ran the checks and it's just the formatter which fails. Indentation is nested where it shouldn't be, and the line might exceed 80 cols which would require spreading it over multiple lines. Would you mind running `stylua` over it?

**Comment by adigitoleo** [comment]
Ah my bad, my own LuaLS must have some done some weird autoformatting. Will fix it tonight.

**Comment by adigitoleo** [comment]
Also, a bit unrelated, but do you know when `nvim_set_option_value` grew the `scope=local` and `buf=nr` options? Becuase `nvim_buf_set_option` (as well as `nvim_win_set_option` and the getters) are used a lot in this plugin but they are deprecated in 0.10.

Tried searching for anything in `:h news` or `:h news-0.9` but couldn't figure it out. I assume you want to keep 0.9 support for now?

**Comment by SidOfc** [comment]
No problem at all! I'm already humbled by the contribution, many thanks for that! Yeah it'd certainly be good to keep supporting v0.9 for now. I will probably need to do some more research into this deprecation as I did read about it some time ago but can't recall any specifics. For now using the deprecated version will be fine 👍

**Comment by adigitoleo** [comment]
Hopefully that does it. Took the liberty of force-pushing on account of it's just a formatting issue. I should say that I haven't fully checked if this will somehow make `FileType` trigger repeatedly in some cases, although I'm not sure that it's much of a problem anyway.

**Comment by adigitoleo** [comment]
> No problem at all! I'm already humbled by the contribution, many thanks for that! Yeah it'd certainly be good to keep supporting v0.9 for now. I will probably need to do some more research into this deprecation as I did read about it some time ago but can't recall any specifics. For now using the deprecated version will be fine 👍

Found the PR: https://github.com/neovim/neovim/pull/21474

Has been deprecated since before 0.9 that's why I couldn't see it. Looks like the main difference is using window ID instead of window number. I've recently been working on my own floating term/man/help plugin so that's why I noticed. My writeup of the current caveats with ID/number for windows/buffers might be of interest: https://github.com/neovim/neovim/discussions/30073

**Comment by SidOfc** [comment]
Ah cheers, I'll take some time soonish to update the Carbon's API in a backwards compatible way. For now I won't create an entire release around this one commit but it's pushed to master and can be installed by running your package manager's standard update command :)

Thanks again for the fix and the additional formatting change. Good luck on your plugin too and I'm sure the maintainers of nvim will take any parts of your feedback they deem valid to heart :)

**Pull request merged**
