### PR TITLE
Fix better defaults

### PR DESCRIPTION
**Pull request by saccarosium**
Changes:
* link by default almost all highlight groups to a defalt one (looks good on multiple colorschemes)
* Define split action with <C-x> and <C-s> since they both beave the same in vim
* Setting action 'create file' both on 'c' and '%' for making sense for netrw users
* Using 'u' instead of '.' because is confusing. Normally '.' repeat the last action, 'u' undo stuff is more inline with resetting

### CODE REVIEW

**Comment by SidOfc** [comment]
These changes look more sensible than the ones I picked indeed. Looks like I need to patch some tests to support behavior which the plugin itself does support.

Would you also be up for updating the relevant documentation in the following sections?

- `:h carbon-setting-actions-create`
- `:h carbon-setting-actions-split`
- `:h carbon-setting-highlights-CarbonExe`
- `:h carbon-setting-highlights-CarbonSymlink`
- `:h carbon-setting-highlights-CarbonBrokenSymlink`
- `:h carbon-setting-highlights-CarbonDanger`
- `:h carbon-setting-highlights-CarbonPending`

In the meantime I'll fix the test suite :)

Note to self: Also realizing that the README has a "Mappings" section which will need some updating, and perhaps a disclaimer that the mapping used in the gif no longer reflects the current default.

**Comment by SidOfc** [comment]
I've written a patch for the tests but am not allowed to push to this PR branch. Would you mind [granting access](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) so I can also push changes directly to this PR?

**Comment by SidOfc** [comment]
@saccarosium Unfortunately I'm still locked out:

image

**Comment by saccarosium** [comment]
Screenshot 2022-11-23 at 12 33 31

Very strange

**Comment by SidOfc** [comment]
Strange indeed, for context, I was trying to use `gh pr checkout [PR]` from my own repository since that's where the PR is located. Apparently this just doesn't work well so I opted to go for the traditional "clone fork and commit there instead" solution which did work, apologies for the little mishap on my behalf 😅 

All CI checks passed, will do a final manual check before wrapping it all up in a nice release.

**Comment by SidOfc** [comment]
Thank you for your work on these improvements. All feature requests have been processed and a new release has been created: https://github.com/SidOfc/carbon.nvim/releases/tag/v0.16.0.

Cheers 🍻

**Pull request merged**
